import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { increment, decrement } from '../Redux/features/counterSlice'


export default function Home() {
  const {count} = useSelector(store => store.counter)
  const dispatch = useDispatch()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Counter
        </h1>
    <br/> 
    <br/>
        <div className={styles.grid} style={{display: 'flex', flexDirection: 'column', gap: '1rem'}}>
          <h1>{count}</h1>
          <button onClick={() => dispatch(increment())}>Increase</button>
          <button 
            onClick={() => 
              {if(count === 0) return
              else dispatch(decrement())}
          }>Decrease</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
